[assets]
source = 'assets/images'
destination = 'assets/resources'

[[assets.importers]]
type = 'Texture'
extensions = [
    '.png',
    '.jpg',
    '.jpeg',
    '.bmp',
    '.tga',
    '.psd', # Yes, we do supports .PSD files.
]

[[assets.importers]]
type = 'Transmission'
extensions = [
    '.obj',
    '.blend',
    '.fbx',
    '.gltf',
    '.dae',
    '.3ds',
]

[[assets.importers]]
type = 'Audio'
extensions = [
    '.mp3',
    '.wav',
    '.ogg',
]