[package]
name = "conrod_example_shared"
version = "0.1.0"
authors = ["mitchmindtree <mitchell.nordine@gmail.com>"]
description = "A small crate for sharing common code between conrod examples."

[dependencies]
conrod_core = { path = "../../conrod_core", version = "0.62" }
rand = "0.5"
